apiVersion: kubeflow.org/v1
kind: PyTorchJob
metadata:
  name: pytorch-mnist-gloo
  namespace: seoeun
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
            - args:
                - --backend
                - gloo
              command:
                - sh
                - -ec
                - |
                  # This is how additional packages can be installed dynamically
                  python3 -m pip install --user --no-warn-script-location tensorboardX
                  # Run the rest of the command after installing the packages.
                  "$0" "$@"
                - python
                - /efs-data/mnist.py
              image: 974643886555.dkr.ecr.ap-northeast-2.amazonaws.com/aladin-runtime:pytorch-llama
              name: pytorch
              volumeMounts:
                - mountPath: /efs-data
                  name: efs-data
          volumes:
            - name: efs-data
              persistentVolumeClaim:
                claimName: efs-data
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
            - args:
                - --backend
                - gloo
              command:
                - sh
                - -ec
                - python3 -m pip install --user --no-warn-script-location tensorboardX && $0 $@
                - python
                - /efs-data/mnist.py
              image: 974643886555.dkr.ecr.ap-northeast-2.amazonaws.com/aladin-runtime:pytorch-llama
              name: pytorch
              volumeMounts:
                - mountPath: /efs-data
                  name: efs-data
          volumes:
            - name: efs-data
              persistentVolumeClaim:
                claimName: efs-data
