apiVersion: v1
kind: Pod
metadata:
  name: gpu
spec:
  containers:
    - name: gpu-container
      image: nvidia/cuda:12.2-runtime
      command:
        - "/bin/sh"
        - "-c"
      args:
        - nvidia-smi && tail -f /dev/null
      resources:
        requests:
          nvidia.com/gpu: 1
        limits:
          nvidia.com/gpu: 1