apiVersion: "kubeflow.org/v1"
kind: PyTorchJob
metadata:
  name: pytorch-mnist
  namespace: kubeflow
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
            - name: pytorch
              image: public.ecr.aws/pytorch-samples/pytorch_dist_mnist:latest
              imagePullPolicy: Always
              command:
                - "python3"
                - "/opt/mnist/src/mnist.py"
                - "--epochs=1"
    Worker:
      replicas: 2
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
            - name: pytorch
              image: public.ecr.aws/pytorch-samples/pytorch_dist_mnist:latest
              imagePullPolicy: Always
              command:
                - "python3"
                - "/opt/mnist/src/mnist.py"
                - "--epochs=1"